    var anchortag = "#services"
    var servername = ".";
    var services = ""
    var usensehome = ""
    var me = "/me.html";
    var measure = "/measure.html";
    var team = "/team.html";
    var purify = "/purify.html";
    var trend = "/trend.html";
    var curier = "/curier.html";
    var evaluate = "/evaluate.html";
    var paris = "/ai1.jpeg"
    var newyork = "/ai2.jpeg"
    var cisco = "/ai5.jpeg"
    var urlnameusensehome = servername + usensehome;
    var urlnameme =  servername + services + me;
    var urlnamemeasure =  servername + services + measure;
    var urlnameteam =  servername + services + team;
    var urlnamepurify =  servername + services + purify;
    var urlnametrend =  servername + services + trend;
    var urlnamecurier =  servername + services + curier;
    var urlnamecurier =  servername + services + curier;
    var urlnameevaluate =  servername + services + evaluate;
    var urlnameparis =  servername + paris;
    var urlnamenewyork =  servername + newyork;
    var urlnamecisco =  servername + cisco;